-- MySQL Script generated by MySQL Workbench
-- Tue May 30 23:36:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema exercicio1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exercicio1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercicio1` DEFAULT CHARACTER SET utf8 ;
USE `exercicio1` ;

-- -----------------------------------------------------
-- Table `exercicio1`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercicio1`.`clientes` (
  `idcliente` INT(11) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercicio1`.`pedidos` (
  `idpedido` INT(11) NOT NULL,
  `data` DATETIME NULL,
  `descricao` VARCHAR(45) NULL,
  `valor` DOUBLE NULL,
  `idcliente` INT(11) NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `idcliente_idx` (`idcliente` ASC),
  CONSTRAINT `idcliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `exercicio1`.`clientes` (`idcliente`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
